name: segue_frontend
description: Flutter frontend for the MCM Last Intent hackathon project.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/mcm/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Variable.ttf
          weight: 900
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
