name: segue_frontend
description: Flutter frontend for the MCM Last Intent hackathon project.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
